### ISSUE TITLE
Handle statutory holidays

### ISSUE THREAD

**Issue by james2doyle** [invokemedia/harvey#1]
Crawl this page as JSON: http://www2.gov.bc.ca/gov/content/employment-business/employment-standards-advice/employment-standards/factsheets/statutory-holidays-in-bc-2017-2020

Convert these pages to JSON?

* https://www.statutoryholidays.com/2017.php
* https://www.statutoryholidays.com/2018.php

Use a self-hosted list of holidays: https://s3-us-west-2.amazonaws.com/invokemedia-alma/holidays.yml

**Comment by wesdeboer** [comment]
Perhaps provide a custom url in json/yml to allow providing custom office closures as different regions and companies will have unique needs.

**Comment by james2doyle** [comment]
Converted to JSON so as to not add another dependency (yaml parser) and added to the same bucket

https://s3-us-west-2.amazonaws.com/invokemedia-alma/holidays.json
